### PR TITLE
(Fix) Disable continue button in step 1 if contracts couldn't be downloaded

### LINKED ISSUE #399: utils.js:37 Error: Returned error: Unexpected token < in JSON at position 0
### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0xe394E2260b012A1A284c8526A3887c786BbE08D3&networkID=1

### Do you have screenshots showing the problem?

image

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

```
attach to crowdsale contract
utils.js:37 Error: Returned error: Unexpected token < in JSON at position 0
    at Object.ErrorResponse (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1388842)
    at https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1506550
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9909:9
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9960:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9837:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9933:18
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3345:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1212:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3431:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1242:16)
    at runReturnHandlers (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9932:15)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4115:24
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4120:13
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1336:9
From previous event:
    at i.h [as _captureStackTrace] (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1420387)
    at i._resolveFromExecutor (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1453642)
    at new i (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1446151)
    at o (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:524759)
    at n (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:239719)
    at Object.d._executeMethod (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1801944)
    at i (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:337796)
    at Object.callback (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:337650)
    at o (https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:239955)
    at https://wizard.oracles.org/static/js/main.38f3f9fa.js:1:1506594
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9909:9
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9960:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:683:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1203:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9837:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9933:18
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3345:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1212:9
    at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3431:24)
    at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1242:16)
    at runReturnHandlers (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9932:15)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:4115:24
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1208:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1193:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1168:16
```
---

### PR DESCRIPTION
**Pull request by fvictorio**
Closes #399.

Disable the "Continue" button in step one until all the contracts are downloaded. If there is a problem with the download, the button is kept disabled and a toast message with an error is shown.

This will help with the problem in #399, but only when the ABI files are missing, because those are the ones that are `JSON.parse`d. If the SOL and BIN files, the index.html is returned. I mean: a 404 error is never returned when a file in `public/contracts` is missing.

I think this is configured that way for `react-router` to work in HTML5 mode. I don't really know how to fix that, but I think it's a different issue.

### CODE REVIEW

File: src/components/stepOne/index.js [hunk 1]
```diff
@@ -56,16 +90,37 @@ export class stepOne extends React.Component {
...
+        () => {
+          this.setState({
+            contractsDownloaded: DOWNLOAD_STATUS.SUCCESS
+          })
+        },
+        (e) => {
+          console.error('Error downloading contracts', e)
+          toast.showToaster({
+            type: TOAST.TYPE.ERROR,
+            message: 'The contracts could not be downloaded'
```
Comment (vbaranov) [inline src/components/stepOne/index.js]: Maybe, to add "Please try to refresh the page. If the problem still persists, try again later".

Comment (fvictorio) [reply src/components/stepOne/index.js]: Updated.
