### PR TITLE
(Fix) manage crowdsale to allow edit if it didn't started yet

### LINKED ISSUE #519: (Bug) Can't edit crowdsale if it didn't started yet
From this comments: 
https://github.com/poanetwork/ico-wizard/issues/484#issuecomment-360286868
https://github.com/poanetwork/ico-wizard/issues/484#issuecomment-360563271

--
In Manage Screen: A crowdsale cannot be edited if it didn't started.

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #519

### CODE REVIEW

File: src/components/manage/utils.js [hunk 1]
```diff
@@ -325,9 +325,14 @@ export const processTier = (crowdsaleAddress, crowdsaleNum) => {
     })
 }
 
-const setCurrentContract = contract => {
+const setCurrentContract = (contract, index) => {
   const currentDate = new Date().getTime()
-  if (contract.startDate <= currentDate && currentDate <= contract.endDate) contract.current = true
+  const { startDate, endDate } = contract
+
+  if (index === 0 && currentDate < startDate || startDate <= currentDate && currentDate <= endDate) {
```
Comment (fvictorio) [inline src/components/manage/utils.js]: This condition is a little hard to read. At the very least we should use parentheses to make the precedence clear:

```
if ((index === 0 && currentDate < startDate) || (startDate <= currentDate && currentDate <= endDate))
```

Even better, extract the sub-conditions to variables:

```
const isActive = startDate <= currentDate && currentDate <= endDate
const isFirstTier = index === 0

if (isActive || (isFirstTier && currentDate < startDate)
```

Comment (fernandomg) [reply src/components/manage/utils.js]: updated, thanks!
