### PR TITLE
(Fix) Calculate gas for tx

### LINKED ISSUE #460: (Fix) For several tiers, some transactions goes out of gas
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Any

### If you were able to create it, what is the URL of your crowdsale?

No

### Do you have screenshots showing the problem?

No

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

### PR DESCRIPTION
**Pull request by fernandomg**
Closes #460 

Calculates gas and sets a default maximum gasLimit for all the tx in the deployment process.

### CODE REVIEW

File: src/utils/blockchainHelpers.js [hunk 1]
```diff
@@ -116,26 +121,23 @@ const deployContractInner = (accounts, abi, deployOpts) => {
   console.log('abi', abi)
 
   const { web3 } = web3Store
-  const estimatedGasMax = 4016260
   const objAbi = JSON.parse(JSON.stringify(abi))
   const contractInstance = new web3.eth.Contract(objAbi)
+  const deploy = contractInstance.deploy(deployOpts)
 
-  return contractInstance.deploy(deployOpts).estimateGas({ gas: estimatedGasMax })
+  return deploy.estimateGas({ gas: calculateGasLimit() })
```
Comment (fvictorio) [inline src/utils/blockchainHelpers.js]: Can we move `estimatedGasMax` to a constant, and use it here? So this line becomes:

```
return deploy.estimateGas({ gas: MAX_GAS_LIMIT })
```

which I feel is the intention, isn't it?

Comment (fernandomg) [reply src/utils/blockchainHelpers.js]: @fvictorio done, thanks!
